spring.application.name=SimpleRuleEngine

spring.datasource.url=jdbc:postgresql://localhost:5432/simple_rule_engine
spring.datasource.username=amrhamdyahmed
spring.datasource.password=
spring.jpa.properties.hibernate.default_schema=simple_rule_engine
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

logging.level.com.simpleRuleEngine=INFO
