spring.application.name=SimpleRuleEngine

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:simple_rule_engine}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=simple_rule_engine
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-postgres.sql

logging.level.com.simpleRuleEngine=INFO
